---
title: "pkglock test"
author: "Brian Schultheiss"
date: "April 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Setup Installer

```{r}
installerdir <- file.path( getwd(),"pkglock/inst/installreq")
dir.create(installerdir, showWarnings = FALSE, recursive = TRUE)
devtools::install_github("bschulth/pkglock", lib=installerdir, force=TRUE, dependencies=TRUE)  
```


# Create runtime descriptor

```{r }

pkgs <- c("R6", "pillar (>= 1.2.1)")
lockdata <- pkglock::gen_packrat_lockfile(
              pkgs,
              github = c("r-lib/pillar"),
              name = "Brian Schultheiss",
              email = "bschulth@amgen.com"
            )


```


# Install from packrat lockfile

```{r }
rtdir <- pkglock::setup_runtime_template(lockdata, .dir = file.path( getwd(),"work"))

binary_runtime <- pkglock::install_runtime(rtdir, installerdir)

```

# Build a descriptor from an R lib.loc

```{r}

pkglist <- pkglock::build_package_list_from_library_dir(.libdir = "C:/dev/apps/R/3.4.3/library")
cat(pkglock::gen_pkg_desc_from_package_list(pkglist, TRUE))

```
